[project]
name = "linux-9-2-hw"
version = "0.1.0"
description = "Домашнее задание по курсу Linux"
authors = [
    { name = "ALEXANDR_SH", email = "sandro.86@bk.ru" }
]
readme = "README.md"
requires-python = ">=3.12"

[tool.poetry.dependencies]
requests = ">=2.32.5"
json-log-formatter = ">=1.1.1"
python-decouple = "^3.8"  # Добавьте этот модуль
colorlog = "^6.10.1"      # И этот модуль

[tool.poetry.group.dev.dependencies]
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "src" }]

[tool.ruff]
line-length = 119
target-version = "py312"
respect-gitignore = true
exclude = [".git", ".ruff_cache", ".venv", "venv"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "UP"]  # Базовые правила
ignore = [
    "E501",  # Игнорировать длину строки
    "ANN401", # Dynamically typed expressions (typing.Any)
    "CPY001", # Missing copyright notice
    "COM812", # Trailing comma missing
    "PLC0414", # Import alias does not rename original package
    "PLR6301"  # Method could be a function
]
preview = false

[tool.ruff.lint.isort]
lines-after-imports = 2
force-sort-within-sections = true
known-first-party = ["src"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "S101", # Use of `assert` detected
    "ANN201", # Missing return type annotation
    "ANN001", # Missing type annotation for argument
    "SLF001", # Private member accessed
    "S105", # Possible hardcoded password
    "S311"  # Standard pseudo-random generators
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.mypy]
python_version = "3.12"
files = "src"
strict = true
exclude = ["venv", ".venv", "build", "dist", "tests"]
show_error_codes = true
ignore_missing_imports = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_no_return = false
warn_unreachable = true
no_implicit_optional = true
allow_redefinition = true


[[tool.mypy.overrides]]
module = "tests.*"
disable_error_code = ["no-untyped-def"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_functions = ["test*"]
addopts = "--cov=src --cov-report term-missing --cov-report xml"

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 80

[tool.poe.tasks]
lint = [
  { cmd = "ruff check src tests" },
  { cmd = "mypy src" }
]
format = [
  { cmd = "ruff check --fix src tests" },
  { cmd = "ruff format src tests" }
]
test = "pytest"
