name: Ruff


on:
  push:
    branches:
      - Feature/homework_13_2

jobs:
  ruff-fix:
    runs-on: ubuntu-latest
    # Принудительно включаем Node.js 24 для всех экшенов в этой джобе
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff fix and format
        run: |
          ruff check --fix .
          ruff format .

      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: fix lint and format with ruff"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@://github.com"
          commit_author: "alysandro <163910150+alysandro@://github.com>"
          # Указываем ветку явно, если нужно
          branch: ${{ github.head_ref || github.ref_name }}
